spring:
  data:
    mongodb:
      uri: mongodb://docker:mongopw@localhost:27017
      host: localhost
      port: 27017
      username: docker
      password: mongopw
      authentication-database: admin
      database: admin